sonar.projectKey=galactusclb_LaunchZap
sonar.organization=galactusclb
sonar.sources=apps/api/src,apps/web/src
sonar.exclusions=**/node_modules/**,**/*.test.ts
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
