FROM node:lts-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml tsconfig.json pnpm-workspace.yaml ./

RUN pnpm install 

COPY . .

RUN DATABASE_URL=postgresql://x:x@localhost:5432/x pnpm run generate

RUN pnpm run build

ENV NODE_ENV=production

EXPOSE 4000

RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]

CMD ["pnpm", "start"]