name: Build & Push to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log
        run: echo "Changes detected in api — will build image from ./api"