name: Build & Push to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Generate Image Tag
        id: tag
        run: echo "value=$(date + '%y%m%d')-$RANDOM" >> $GITHUB_OUTPUT

      - name: Build API Docker Image
        run: |
          docker build -t launchzap-api:${{ steps.tag.outputs.value }} -f Dockerfile.prod ./api